
title: "NBA Data Analytics Using Python Blog" 
email: "agao0224@gmail.com" 
description: "This is my blog portfolio" 
baseurl: "" # the name of the repository 
url: "https://agao0224.github.io" #  change this to "https://<your-github-username>.github.io"
image: "/assets/images/blogheader.jpg"
author: "Adam Gao"
copyright: "AG" # Your initials or what you want the copyright to be.  Leave empty for no copyright
footer_description: 


# Social media users names.  Leave fields blank that you don't want displayed
github_username:  agao0224

